import { Month, Vegetable, VegetableCategory } from '../types/planting';

/**
 * Core data constants for the Vegetable Planting Guide application
 */

/**
 * Month information for the application
 */
export const MONTHS: Month[] = [
  { name: "January", shortName: "Jan", number: 1 },
  { name: "February", shortName: "Feb", number: 2 },
  { name: "March", shortName: "Mar", number: 3 },
  { name: "April", shortName: "Apr", number: 4 },
  { name: "May", shortName: "May", number: 5 },
  { name: "June", shortName: "Jun", number: 6 },
  { name: "July", shortName: "Jul", number: 7 },
  { name: "August", shortName: "Aug", number: 8 },
  { name: "September", shortName: "Sep", number: 9 },
  { name: "October", shortName: "Oct", number: 10 },
  { name: "November", shortName: "Nov", number: 11 },
  { name: "December", shortName: "Dec", number: 12 },
];

/**
 * Comprehensive database of vegetable planting information
 * Contains detailed data about planting times and growing requirements
 * for various vegetables across different USDA hardiness zones.
 */
export const VEGETABLE_DATABASE: Vegetable[] = [
  {
    name: "Tomatoes",
    category: VegetableCategory.FRUIT,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 8, 9] },
      "9": { plantingMonths: [2, 3, 4, 8, 9, 10] },
      "10": { plantingMonths: [1, 2, 3, 9, 10, 11] },
    },
  },
  {
    name: "Carrots",
    category: VegetableCategory.ROOT,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 7, 8, 9] },
      "7": { plantingMonths: [2, 3, 4, 8, 9, 10] },
      "8": { plantingMonths: [1, 2, 3, 9, 10, 11] },
      "9": { plantingMonths: [1, 2, 10, 11, 12] },
      "10": { plantingMonths: [11, 12, 1, 2] },
    },
  },
  {
    name: "Lettuce",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 45,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7, 8] },
      "5": { plantingMonths: [4, 5, 6, 7, 8, 9] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8, 9] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Peppers",
    category: VegetableCategory.FRUIT,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Cucumbers",
    category: VegetableCategory.CUCURBIT,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Broccoli",
    category: VegetableCategory.CRUCIFEROUS,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Spinach",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 45,
    zones: {
      "3": { plantingMonths: [5, 6, 7, 8] },
      "4": { plantingMonths: [4, 5, 6, 7, 8, 9] },
      "5": { plantingMonths: [4, 5, 6, 7, 8, 9] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8, 9] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Green Beans",
    category: VegetableCategory.LEGUME,
    daysToHarvest: 55,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6, 7] },
      "6": { plantingMonths: [4, 5, 6, 7] },
      "7": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    },
  },
  {
    name: "Zucchini",
    category: VegetableCategory.CUCURBIT,
    daysToHarvest: 50,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Kale",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 55,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Radishes",
    category: VegetableCategory.ROOT,
    daysToHarvest: 30,
    zones: {
      "3": { plantingMonths: [5, 6, 7, 8] },
      "4": { plantingMonths: [4, 5, 6, 7, 8, 9] },
      "5": { plantingMonths: [4, 5, 6, 7, 8, 9] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8, 9] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Potatoes",
    category: VegetableCategory.ROOT,
    daysToHarvest: 100,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [3, 4, 5, 6] },
      "7": { plantingMonths: [2, 3, 4, 5, 6] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6] },
    },
  },
  {
    name: "Onions",
    category: VegetableCategory.ALLIUM,
    daysToHarvest: 100,
    zones: {
      "3": { plantingMonths: [4, 5] },
      "4": { plantingMonths: [3, 4, 5] },
      "5": { plantingMonths: [3, 4, 5] },
      "6": { plantingMonths: [2, 3, 4, 5] },
      "7": { plantingMonths: [2, 3, 4, 5] },
      "8": { plantingMonths: [1, 2, 3, 4, 5] },
      "9": { plantingMonths: [1, 2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Garlic",
    category: VegetableCategory.ALLIUM,
    daysToHarvest: 240,
    zones: {
      "3": { plantingMonths: [9, 10] },
      "4": { plantingMonths: [9, 10] },
      "5": { plantingMonths: [9, 10] },
      "6": { plantingMonths: [9, 10, 11] },
      "7": { plantingMonths: [9, 10, 11] },
      "8": { plantingMonths: [9, 10, 11] },
      "9": { plantingMonths: [9, 10, 11] },
      "10": { plantingMonths: [9, 10, 11] },
    },
  },
  {
    name: "Cauliflower",
    category: VegetableCategory.CRUCIFEROUS,
    daysToHarvest: 80,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6, 7] },
      "6": { plantingMonths: [3, 4, 5, 6, 7] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    },
  },
  {
    name: "Eggplant",
    category: VegetableCategory.FRUIT,
    daysToHarvest: 75,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Sweet Potatoes",
    category: VegetableCategory.ROOT,
    daysToHarvest: 120,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9] },
    },
  },
  {
    name: "Brussels Sprouts",
    category: VegetableCategory.CRUCIFEROUS,
    daysToHarvest: 90,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6, 7] },
      "6": { plantingMonths: [3, 4, 5, 6, 7] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    },
  },
  {
    name: "Cabbage",
    category: VegetableCategory.CRUCIFEROUS,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6, 7] },
      "6": { plantingMonths: [3, 4, 5, 6, 7] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    },
  },
  {
    name: "Beets",
    category: VegetableCategory.ROOT,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Swiss Chard",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 55,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Pumpkins",
    category: VegetableCategory.CUCURBIT,
    daysToHarvest: 100,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Winter Squash",
    category: VegetableCategory.CUCURBIT,
    daysToHarvest: 100,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Turnips",
    category: VegetableCategory.ROOT,
    daysToHarvest: 50,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Parsnips",
    category: VegetableCategory.ROOT,
    daysToHarvest: 120,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [3, 4, 5, 6] },
      "7": { plantingMonths: [2, 3, 4, 5, 6] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6] },
    },
  },
  {
    name: "Collard Greens",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6, 7] },
      "6": { plantingMonths: [3, 4, 5, 6, 7] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
    },
  },
  {
    name: "Okra",
    category: VegetableCategory.FRUIT,
    daysToHarvest: 55,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Artichokes",
    category: VegetableCategory.PERENNIAL,
    daysToHarvest: 180,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [4, 5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [3, 4, 5] },
      "7": { plantingMonths: [2, 3, 4, 5] },
      "8": { plantingMonths: [1, 2, 3, 4, 5] },
      "9": { plantingMonths: [1, 2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Asparagus",
    category: VegetableCategory.PERENNIAL,
    daysToHarvest: 730,
    zones: {
      "3": { plantingMonths: [4, 5] },
      "4": { plantingMonths: [3, 4, 5] },
      "5": { plantingMonths: [3, 4, 5] },
      "6": { plantingMonths: [2, 3, 4, 5] },
      "7": { plantingMonths: [2, 3, 4, 5] },
      "8": { plantingMonths: [1, 2, 3, 4, 5] },
      "9": { plantingMonths: [1, 2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Rhubarb",
    category: VegetableCategory.PERENNIAL,
    daysToHarvest: 365,
    zones: {
      "3": { plantingMonths: [4, 5] },
      "4": { plantingMonths: [3, 4, 5] },
      "5": { plantingMonths: [3, 4, 5] },
      "6": { plantingMonths: [2, 3, 4, 5] },
      "7": { plantingMonths: [2, 3, 4, 5] },
      "8": { plantingMonths: [1, 2, 3, 4, 5] },
      "9": { plantingMonths: [1, 2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Leeks",
    category: VegetableCategory.ALLIUM,
    daysToHarvest: 120,
    zones: {
      "3": { plantingMonths: [4, 5] },
      "4": { plantingMonths: [3, 4, 5] },
      "5": { plantingMonths: [3, 4, 5] },
      "6": { plantingMonths: [2, 3, 4, 5] },
      "7": { plantingMonths: [2, 3, 4, 5] },
      "8": { plantingMonths: [1, 2, 3, 4, 5] },
      "9": { plantingMonths: [1, 2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Shallots",
    category: VegetableCategory.ALLIUM,
    daysToHarvest: 100,
    zones: {
      "3": { plantingMonths: [4, 5] },
      "4": { plantingMonths: [3, 4, 5] },
      "5": { plantingMonths: [3, 4, 5] },
      "6": { plantingMonths: [2, 3, 4, 5] },
      "7": { plantingMonths: [2, 3, 4, 5] },
      "8": { plantingMonths: [1, 2, 3, 4, 5] },
      "9": { plantingMonths: [1, 2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Fennel",
    category: VegetableCategory.HERB,
    daysToHarvest: 90,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [3, 4, 5, 6] },
      "7": { plantingMonths: [2, 3, 4, 5, 6] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6] },
    },
  },
  {
    name: "Celery",
    category: VegetableCategory.OTHER,
    daysToHarvest: 100,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [3, 4, 5, 6] },
      "7": { plantingMonths: [2, 3, 4, 5, 6] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6] },
    },
  },
  {
    name: "Endive",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 85,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Arugula",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 40,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Mustard Greens",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 45,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Watermelon",
    category: VegetableCategory.FRUIT,
    daysToHarvest: 85,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Cantaloupe",
    category: VegetableCategory.FRUIT,
    daysToHarvest: 80,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Corn",
    category: VegetableCategory.OTHER,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Bok Choy",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 45,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Kohlrabi",
    category: VegetableCategory.CRUCIFEROUS,
    daysToHarvest: 55,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Rutabaga",
    category: VegetableCategory.ROOT,
    daysToHarvest: 90,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [4, 5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [3, 4, 5, 6] },
      "7": { plantingMonths: [2, 3, 4, 5, 6] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6] },
    },
  },
  {
    name: "Daikon",
    category: VegetableCategory.ROOT,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Bitter Melon",
    category: VegetableCategory.FRUIT,
    daysToHarvest: 85,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Jicama",
    category: VegetableCategory.ROOT,
    daysToHarvest: 150,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Taro",
    category: VegetableCategory.ROOT,
    daysToHarvest: 200,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Malabar Spinach",
    category: VegetableCategory.LEAFY,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Luffa",
    category: VegetableCategory.CUCURBIT,
    daysToHarvest: 120,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Yardlong Beans",
    category: VegetableCategory.LEGUME,
    daysToHarvest: 80,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Chayote",
    category: VegetableCategory.CUCURBIT,
    daysToHarvest: 120,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Winged Bean",
    category: VegetableCategory.LEGUME,
    daysToHarvest: 75,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Oca",
    category: VegetableCategory.ROOT,
    daysToHarvest: 180,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Ulluco",
    category: VegetableCategory.ROOT,
    daysToHarvest: 180,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Mashua",
    category: VegetableCategory.ROOT,
    daysToHarvest: 180,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Yacon",
    category: VegetableCategory.ROOT,
    daysToHarvest: 200,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Basil",
    category: VegetableCategory.HERB,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Rosemary",
    category: VegetableCategory.HERB,
    daysToHarvest: 90,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Thyme",
    category: VegetableCategory.HERB,
    daysToHarvest: 75,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Oregano",
    category: VegetableCategory.HERB,
    daysToHarvest: 80,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Sage",
    category: VegetableCategory.HERB,
    daysToHarvest: 75,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Mint",
    category: VegetableCategory.HERB,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Lavender",
    category: VegetableCategory.HERB,
    daysToHarvest: 90,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Dill",
    category: VegetableCategory.HERB,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Cilantro",
    category: VegetableCategory.HERB,
    daysToHarvest: 45,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Parsley",
    category: VegetableCategory.HERB,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6, 7] },
      "4": { plantingMonths: [4, 5, 6, 7] },
      "5": { plantingMonths: [4, 5, 6, 7, 8] },
      "6": { plantingMonths: [3, 4, 5, 6, 7, 8] },
      "7": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "8": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      "9": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] },
    },
  },
  {
    name: "Chives",
    category: VegetableCategory.HERB,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Tarragon",
    category: VegetableCategory.HERB,
    daysToHarvest: 90,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Marjoram",
    category: VegetableCategory.HERB,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Lemongrass",
    category: VegetableCategory.HERB,
    daysToHarvest: 100,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Stevia",
    category: VegetableCategory.HERB,
    daysToHarvest: 90,
    zones: {
      "3": { plantingMonths: [5] },
      "4": { plantingMonths: [5] },
      "5": { plantingMonths: [4, 5] },
      "6": { plantingMonths: [4, 5] },
      "7": { plantingMonths: [3, 4, 5] },
      "8": { plantingMonths: [2, 3, 4, 5] },
      "9": { plantingMonths: [2, 3, 4, 5] },
      "10": { plantingMonths: [1, 2, 3, 4, 5] },
    },
  },
  {
    name: "Lemon Balm",
    category: VegetableCategory.HERB,
    daysToHarvest: 70,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Catnip",
    category: VegetableCategory.HERB,
    daysToHarvest: 80,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  },
  {
    name: "Borage",
    category: VegetableCategory.HERB,
    daysToHarvest: 60,
    zones: {
      "3": { plantingMonths: [5, 6] },
      "4": { plantingMonths: [5, 6] },
      "5": { plantingMonths: [4, 5, 6] },
      "6": { plantingMonths: [4, 5, 6] },
      "7": { plantingMonths: [3, 4, 5, 6, 7] },
      "8": { plantingMonths: [2, 3, 4, 5, 6, 7, 8] },
      "9": { plantingMonths: [2, 3, 4, 5, 6, 7, 8, 9] },
      "10": { plantingMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
    },
  }
];

/**
 * Companion plant recommendations
 */
export const COMPANION_PLANTS: { [key: string]: string[] } = {
  "Tomatoes": ["Basil", "Marigolds", "Garlic", "Onions"],
  "Carrots": ["Rosemary", "Sage", "Onions", "Lettuce"],
  "Lettuce": ["Carrots", "Radishes", "Strawberries", "Cucumbers"],
  "Peppers": ["Basil", "Oregano", "Marjoram", "Onions"],
  "Cucumbers": ["Dill", "Marigolds", "Nasturtiums", "Radishes"],
  "Broccoli": ["Dill", "Rosemary", "Sage", "Mint"],
  "Spinach": ["Strawberries", "Radishes", "Lettuce", "Onions"],
  "Green Beans": ["Corn", "Potatoes", "Cucumbers", "Strawberries"],
  "Zucchini": ["Nasturtiums", "Marigolds", "Radishes", "Peas"],
  "Kale": ["Dill", "Mint", "Sage", "Thyme"],
  "Radishes": ["Lettuce", "Spinach", "Carrots", "Cucumbers"],
  "Potatoes": ["Horseradish", "Marigolds", "Beans", "Corn"],
  "Onions": ["Carrots", "Beets", "Lettuce", "Chamomile"],
  "Garlic": ["Tomatoes", "Peppers", "Potatoes", "Cabbage"],
  "Cauliflower": ["Celery", "Beans", "Spinach", "Peas"],
  "Eggplant": ["Marigolds", "Beans", "Peppers", "Spinach"],
  "Sweet Potatoes": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Brussels Sprouts": ["Dill", "Sage", "Thyme", "Mint"],
  "Cabbage": ["Dill", "Sage", "Thyme", "Mint"],
  "Beets": ["Onions", "Lettuce", "Cabbage", "Garlic"],
  "Swiss Chard": ["Onions", "Garlic", "Beans", "Cabbage"],
  "Pumpkins": ["Corn", "Beans", "Marigolds", "Nasturtiums"],
  "Winter Squash": ["Corn", "Beans", "Marigolds", "Nasturtiums"],
  "Turnips": ["Peas", "Beans", "Lettuce", "Spinach"],
  "Parsnips": ["Onions", "Radishes", "Lettuce", "Peas"],
  "Collard Greens": ["Dill", "Mint", "Sage", "Thyme"],
  "Okra": ["Peppers", "Eggplant", "Basil", "Marigolds"],
  "Artichokes": ["Tarragon", "Cabbage", "Peas", "Sunflowers"],
  "Asparagus": ["Basil", "Parsley", "Tomatoes", "Marigolds"],
  "Rhubarb": ["Strawberries", "Beans", "Cabbage", "Kale"],
  "Leeks": ["Carrots", "Celery", "Onions", "Beets"],
  "Shallots": ["Carrots", "Beets", "Lettuce", "Chamomile"],
  "Fennel": ["Dill", "Coriander", "Mint", "Sage"],
  "Celery": ["Beans", "Cabbage", "Onions", "Tomatoes"],
  "Endive": ["Radishes", "Lettuce", "Spinach", "Onions"],
  "Arugula": ["Lettuce", "Spinach", "Radishes", "Onions"],
  "Mustard Greens": ["Dill", "Mint", "Sage", "Thyme"],
  "Watermelon": ["Corn", "Radishes", "Marigolds", "Nasturtiums"],
  "Cantaloupe": ["Corn", "Radishes", "Marigolds", "Nasturtiums"],
  "Corn": ["Beans", "Squash", "Cucumbers", "Peas"],
  "Bok Choy": ["Carrots", "Beets", "Lettuce", "Spinach"],
  "Kohlrabi": ["Beets", "Onions", "Cucumbers", "Lettuce"],
  "Rutabaga": ["Peas", "Beans", "Lettuce", "Spinach"],
  "Daikon": ["Lettuce", "Spinach", "Carrots", "Cucumbers"],
  "Bitter Melon": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Jicama": ["Corn", "Beans", "Marigolds", "Nasturtiums"],
  "Taro": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Malabar Spinach": ["Beans", "Corn", "Cucumbers", "Peppers"],
  "Luffa": ["Corn", "Beans", "Marigolds", "Nasturtiums"],
  "Yardlong Beans": ["Corn", "Cucumbers", "Potatoes", "Strawberries"],
  "Chayote": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Winged Bean": ["Corn", "Cucumbers", "Potatoes", "Strawberries"],
  "Oca": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Ulluco": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Mashua": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Yacon": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Basil": ["Tomatoes", "Peppers", "Oregano", "Marigolds"],
  "Rosemary": ["Sage", "Thyme", "Carrots", "Beans"],
  "Thyme": ["Cabbage", "Broccoli", "Eggplant", "Strawberries"],
  "Oregano": ["Peppers", "Tomatoes", "Basil", "Marigolds"],
  "Sage": ["Rosemary", "Cabbage", "Carrots", "Strawberries"],
  "Mint": ["Cabbage", "Tomatoes", "Peppers", "Broccoli"],
  "Lavender": ["Rosemary", "Sage", "Thyme", "Oregano"],
  "Dill": ["Cabbage", "Cucumbers", "Lettuce", "Onions"],
  "Cilantro": ["Spinach", "Lettuce", "Tomatoes", "Peppers"],
  "Parsley": ["Tomatoes", "Asparagus", "Corn", "Peppers"],
  "Chives": ["Carrots", "Tomatoes", "Broccoli", "Cabbage"],
  "Tarragon": ["Eggplant", "Peppers", "Tomatoes", "Marigolds"],
  "Marjoram": ["Carrots", "Peppers", "Tomatoes", "Basil"],
  "Lemongrass": ["Basil", "Mint", "Marigolds", "Nasturtiums"],
  "Stevia": ["Basil", "Mint", "Marigolds", "Nasturtiums"],
  "Lemon Balm": ["Tomatoes", "Peppers", "Basil", "Marigolds"],
  "Catnip": ["Beans", "Corn", "Marigolds", "Nasturtiums"],
  "Borage": ["Tomatoes", "Strawberries", "Squash", "Cucumbers"]
}; 